TELEGRAM_BOT_TOKEN = "XXXXXXXXXXXX"
NGROK_AUTH_TOKEN = "XXXXXXXXXXXX"

ALLOWED_USERS = ["XXXXXXXXXXXX", "XXXXXXXXXXXX"]

DAPS_URL = "localhost:3100"
DAPS_BACKEND_ENV_FILE = "/home/agp/dev/daps/backend/.env"
DAPS_BACKEND_ENV_FILE_COPY = "/home/agp/dev/daps/backend/.env.copy"
